pipeline:
  name: flexiTemplatePipeline1
  identifier: flexiTemplatePipeline1
  tags: {}
  template:
    templateRef: PipelineTemplateFlexi24Feb
    versionLabel: v1
    templateInputs:
      stages:
        - parallel:
            - stage:
                identifier: stage1
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - parallel:
                          - insert:
                              identifier: insert1
                              steps: <+input>
                          - step:
                              identifier: ShellScript_1
                              type: ShellScript
                              spec:
                                source:
                                  type: Inline
                                  spec:
                                    script: <+input>
                      - insert:
                          identifier: insert2
                          steps: <+input>
            - stage:
                identifier: stage2
                template:
                  templateInputs:
                    type: Deployment
                    spec:
                      environment:
                        environmentRef: <+input>
                        environmentInputs: <+input>
                        serviceOverrideInputs: <+input>
                        infrastructureDefinitions: <+input>
                      service:
                        serviceRef: <+input>
                        serviceInputs: <+input>
                      execution:
                        steps:
                          - parallel:
                              - stepGroup:
                                  identifier: testGroup1
                                  template:
                                    templateInputs:
                                      steps:
                                        - step:
                                            identifier: stepTemplate1
                                            template:
                                              templateInputs:
                                                type: ShellScript
                                                spec:
                                                  source:
                                                    type: Inline
                                                    spec:
                                                      script: <+input>
                                                  environmentVariables:
                                                    - name: inp1
                                                      type: String
                                                      value: <+input>
                                                    - name: inp2
                                                      type: String
                                                      value: <+input>
                                        - stepGroup:
                                            identifier: stepGroup1
                                            steps:
                                              - step:
                                                  identifier: stepTemplate4
                                                  template:
                                                    templateInputs:
                                                      type: ShellScript
                                                      spec:
                                                        source:
                                                          type: Inline
                                                          spec:
                                                            script: <+input>
                                                        environmentVariables:
                                                          - name: inp1
                                                            type: String
                                                            value: <+input>
                                                          - name: inp2
                                                            type: String
                                                            value: <+input>
                                            variables:
                                              - name: var3
                                                type: String
                                                value: <+input>
                                              - name: var4
                                                type: String
                                                value: <+input>
                                      variables:
                                        - name: var1
                                          type: String
                                          value: <+input>
                                        - name: var2
                                          type: String
                                          value: <+input>
                              - insert:
                                  identifier: insert1
                                  steps: <+input>
                          - step:
                              identifier: step123
                              template:
                                templateInputs:
                                  type: ShellScript
                                  spec:
                                    source:
                                      type: Inline
                                      spec:
                                        script: <+input>
                                    environmentVariables:
                                      - name: inp1
                                        type: String
                                        value: <+input>
                                      - name: inp2
                                        type: String
                                        value: <+input>
                          - insert:
                              identifier: insert2
                              steps: <+input>
                        rollbackSteps:
                          - parallel:
                              - stepGroup:
                                  identifier: rollbackCheck1
                                  template:
                                    templateInputs:
                                      steps:
                                        - step:
                                            identifier: stepTemplate1
                                            template:
                                              templateInputs:
                                                type: ShellScript
                                                spec:
                                                  source:
                                                    type: Inline
                                                    spec:
                                                      script: <+input>
                                                  environmentVariables:
                                                    - name: inp1
                                                      type: String
                                                      value: <+input>
                                                    - name: inp2
                                                      type: String
                                                      value: <+input>
                                        - stepGroup:
                                            identifier: stepGroup1
                                            steps:
                                              - step:
                                                  identifier: stepTemplate4
                                                  template:
                                                    templateInputs:
                                                      type: ShellScript
                                                      spec:
                                                        source:
                                                          type: Inline
                                                          spec:
                                                            script: <+input>
                                                        environmentVariables:
                                                          - name: inp1
                                                            type: String
                                                            value: <+input>
                                                          - name: inp2
                                                            type: String
                                                            value: <+input>
                                            variables:
                                              - name: var3
                                                type: String
                                                value: <+input>
                                              - name: var4
                                                type: String
                                                value: <+input>
                                      variables:
                                        - name: var1
                                          type: String
                                          value: <+input>
                                        - name: var2
                                          type: String
                                          value: <+input>
                              - insert:
                                  identifier: insert3
                                  steps: <+input>
                          - insert:
                              identifier: insert4
                              steps: <+input>
        - insert:
            identifier: insert3
            stages: <+input>
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
