pipeline:
  name: Issue check23Dec
  identifier: Issue_check23Dec
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        template:
          templateRef: Nov22Stage
          versionLabel: v1
