pipeline:
  name: pipe3Feb1NonDefault
  identifier: pipe3Feb1NonDefault
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: qaStageMainDec19
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: dasf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
    - stage:
        name: s2
        identifier: s2
        template:
          templateRef: Stage6Caching
          versionLabel: "1"
          templateInputs:
            type: Deployment
            spec:
              infrastructure:
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
                    namespace: <+input>
    - stage:
        name: s3
        identifier: s3
        template:
          templateRef: Stage2Caching
          versionLabel: "1"
          templateInputs:
            type: Deployment
            spec:
              infrastructure:
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
                    namespace: <+input>
