pipeline:
  name: pipe policy 26 may
  identifier: pipe_policy_26_may
  projectIdentifier: DoNotDelete_AmitSingh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ghvj
        identifier: ghvj
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: s1
          environment:
            environmentRef: E1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: I1
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: s123
        identifier: s123
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  timeout: 10m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo non def brnach
                    environmentVariables: []
                    outputVariables: []
        tags: {}
