pipeline:
  name: RemotePipe08Dec
  identifier: RemotePipe08Dec
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: adsaaaaaaa
        identifier: adsaaaaaaa
        template:
          templateRef: customStage23Nov
          versionLabel: v1
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: A34
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
    - stage:
        name: erf
        identifier: erf
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: fgr
                  identifier: fgr
                  template:
                    templateRef: customTemplate
                    versionLabel: v1
                    templateInputs:
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
        tags: {}
    - stage:
        name: rty
        identifier: rty
        template:
          templateRef: git_testtemplate
          versionLabel: "1"
  properties:
    ci:
      codebase:
        connectorRef: account.github_repo_http_delegate_connector
        build: <+input>
