pipeline:
  name: testRef12NovNew
  identifier: testRef12NovNew
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: s23
                  identifier: s23
                  template:
                    templateRef: step2oct17Amit
                    versionLabel: "1"
        tags: {}
