pipeline:
  name: testPipeline05Jan
  identifier: testPipeline05Jan
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: S12
        identifier: S12
        tags: {}
        template:
          templateRef: template5Jan
          versionLabel: "1"
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: ShellScript_1
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
