pipeline:
  name: without git sync
  identifier: without_git_sync
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S12
        identifier: S12
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: ShellScript_1
                  identifier: ShellScript_1
                  template:
                    templateRef: non_gitsync_template_10oct
                    versionLabel: "1"
                    gitBranch: 8march
                    templateInputs:
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
        tags: {}
