pipeline:
  name: Remote Pipeine
  identifier: Remote_Pipeine
  projectIdentifier: Pankaj
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_4
                  identifier: ShellScript_4
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo Hello World 4
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
              - step:
                  type: ShellScript
                  name: ShellScript_5
                  identifier: ShellScript_5
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo Hello World 4
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
